name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "ys1000"
          git config user.email "jerry@jibudata.com"

      - name: Add Helm Chart dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add clusterpedia https://clusterpedia-io.github.io/clusterpedia-helm

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"